In [1]:
%load_ext autoreload

In [63]:
%autoreload
import numpy as np
import darkhistory.electrons.ics.series as series
import darkhistory.electrons.ics.ics_spectrum as ics_spec
import darkhistory.physics as phys

np.set_printoptions(precision=6)

In [68]:
ics_spec.engloss_spec(np.array([7e6], dtype='float128'), np.array([1e4], dtype='float128'), 1000*phys.TCMB(1))


Computing energy loss spectra by analytic series...
Computing upscattering loss spectra...
Computing series 1/7...
Computing series 2/7...
Computing series 3/7...
Computing series 4/7...
Computing series 5/7...
Computing series 6/7...
Computing series 7/7...
Computing downscattering loss spectra...
Computing series 1/7...
Computing series 2/7...
Computing series 3/7...
Computing series 4/7...
Computing series 5/7...
Computing series 6/7...
Computing series 7/7...
***** Diagnostics *****
lowlim_up:  [[ 56.9515]]
lowlim_down:  [[ 42634.5]]
beta:  [ 0.997332]
delta/T:  [ 42577.6]
***** Individual terms *****
term_1_up:  [[ 3.18521e-23]]
term_0_up:  [[-3.89617e-22]]
term_inv_up:  [[-6.23996e-23]]
term_log_up:  [[ nan]]
term_1_down:  [[ 0.0]]
term_0_down:  [[ 0.0]]
term_inv_down:  [[ 0.0]]
term_log_down:  [[ 0.0]]
***** Total Sum (Excluding Prefactor) *****
Upscattering loss spectrum: 
[[ nan]]
Downscattering loss spectrum: 
[[ 0.0]]
***** End Diagnostics *****


/Users/hongwan/GitHub/DarkHistory/darkhistory/electrons/ics/series.py:1050: RuntimeWarning: overflow encountered in exp
  # Extend a to a 2D array.
/Users/hongwan/GitHub/DarkHistory/darkhistory/electrons/ics/series.py:1056: RuntimeWarning: invalid value encountered in multiply
  
/Users/hongwan/GitHub/DarkHistory/darkhistory/electrons/ics/series.py:898: RuntimeWarning: overflow encountered in exp
  return expr
/Users/hongwan/GitHub/DarkHistory/darkhistory/electrons/ics/series.py:899: RuntimeWarning: invalid value encountered in multiply
  


array([[ nan]], dtype=float128)

In [113]:
a = np.array([-1e-8,1e-4, 1])
beta = np.array([1e-8, 1e-3,1.-1e-8])
lowlim1 = np.outer((1-beta)/(2*beta), a)
lowlim2 = np.outer(-(1+beta)/(2*beta), a)
lowlim = np.maximum(lowlim1, lowlim2)
print(lowlim)
print(series.F_log_a(lowlim, a))

[[  5.000000e-01   5.000000e+03   5.000000e+07]
 [  5.005000e-06   4.995000e-02   4.995000e+02]
 [  1.000000e-08   5.000000e-13   5.000000e-09]]
(array([[ 0.0775888,  0.0,  0.0],
       [-73.7552, -3.85918,  7.30347e-217],
       [-170.577, -216.087,  1.11786]], dtype=float128), array([[ 3.84965e-11,  0.0,  0.0],
       [ 5.24232e-12,  6.02323e-11,  0.0],
       [ 2.26671e-12,  9.11894e-11,  1.47179e-11]], dtype=float128))


In [114]:
series.F_x_log(np.array([0.203]), np.array([3.650]))

(array([ 0.0731666], dtype=float128), array([ 1.78408e-11], dtype=float128))

In [116]:
a = np.array([-1e-8,-1e-4,1e-4, 1])
beta = np.array([1e-8, 1e-3,1.-1e-8])
lowlim1 = np.outer((1-beta)/(2*beta), a)
lowlim2 = np.outer(-(1+beta)/(2*beta), a)
lowlim = np.maximum(lowlim1, lowlim2)
print(lowlim)
print(series.F_x_log_a(lowlim, a))

[[  5.000000e-01   5.000000e+03   5.000000e+03   5.000000e+07]
 [  5.005000e-06   5.005000e-02   4.995000e-02   4.995000e+02]
 [  1.000000e-08   1.000000e-04   5.000000e-13   5.000000e-09]]
(array([[ 0.533462,  0.0,  0.0,  0.0],
       [-0.24203, -0.0446386, -0.0443266,  3.65539e-214],
       [-0.242096, -0.241163, -0.241075,  1.27739]], dtype=float128), array([[ 4.71226e-11,  0.0,  0.0,  0.0],
       [ 2.529e-11,  1.06359e-11,  1.07121e-11,  0.0],
       [ 2.52831e-11,  2.53791e-11,  2.53919e-11,  2.87272e-11]], dtype=float128))


In [70]:
np.exp(100)

2.6881171418161356e+43