In [3]:
%load_ext autoreload

In [54]:
%autoreload
import numpy as np
import darkhistory.electrons.ics.ics_spectrum as ics_spec
import darkhistory.physics as phys
import pickle

np.set_printoptions(precision=6)

In [55]:
Emax = np.float128(1e10)
Emin = np.float128(1e-8)
nEe = np.float128(5)
nEp  = np.float128(5)

dlnEp = np.log(Emax/Emin)/nEp
lowengEp = Emin*np.exp((np.arange(nEp)+0.5)*dlnEp)        

dlnEe = np.log(Emax/Emin)/nEe
lowengEe = phys.me + Emin*np.exp((np.arange(nEe)+0.5)*dlnEe)

# lowengEe = np.array([lowengEe[168]],dtype='float128')
# lowengEp = np.array([lowengEp[521]],dtype='float128')
#521
T = np.float128(phys.TCMB(1)*1000)

In [58]:
# %%prun
a = ics_spec.nonrel_spec(lowengEe, lowengEp, T, as_pairs=True)

Initializing...
where_diff on (eleceng, photeng) grid: 
[ True  True False False False]
[ 510999.0  510999.0]
[ 6.30957e-07  0.00251189]
Computing spectra by an expansion in beta...
Computing Q and K terms...
Computing H and G terms...
Computation by expansion in beta complete!
Computing errors for beta expansion method...
spec from nonrel_spec_diff: 
[ 3.89728e-08  0.000154326  0.0  0.0  0.0]
epsrel from nonrel_spec_diff: 
[ 2.48366e-24  3.84178e-17  0.0  0.0  0.0]
where_series on (eleceng, photeng) grid: 
[False False  True  True  True]
Computing spectra by analytic series...
Computing series 1/8...
Computing series 2/8...
Computing series 3/8...
Computing series 4/8...
Computing series 5/8...
Computing series 6/8...
Computing series 7/8...
Computing series 8/8...
Computation by analytic series complete!
spec from nonrel_spec_series: 
[ 0.0  0.0  8.68646e-18  0.0  6.98765e-761]
*********************
Final Result: 
[ 3.89728e-08  0.000154326  8.68646e-18  0.0  6.98765e-761]
Spectrum c

In [43]:
print(a)

[[ 7.59911e-10  1.15017e-09  1.74086e-09 ...,  0.0  0.0  0.0]
 [ 7.59911e-10  1.15017e-09  1.74086e-09 ...,  0.0  0.0  0.0]
 [ 7.59911e-10  1.15017e-09  1.74086e-09 ...,  0.0  0.0  0.0]
 ..., 
 [ 2.08017e-16  3.08421e-16  4.56581e-16 ...,  2.14585e-44  7.38528e-62
   2.71474e-88]
 [ 9.12848e-17  1.35117e-16  1.99798e-16 ...,  1.32491e-25  3.19473e-33
   9.29649e-45]
 [ 3.994e-17  5.90747e-17  8.73106e-17 ...,  1.26754e-17  6.1502e-21
   5.77107e-26]]


In [5]:
# pickle.dump(a, 
#             open("/Users/hongwan/Dropbox (MIT)/Photon Deposition/ICS_nonrel.raw", "wb"))