In [2]:
%load_ext autoreload

In [8]:
%autoreload
import numpy as np
import scipy.special as sp
import darkhistory.electrons.ics.series as series
import darkhistory.electrons.ics.ics_spectrum as ics_spec
import darkhistory.physics as phys
import pickle

np.set_printoptions(precision=6)

In [32]:
beta = np.float128(2e-3)
eleceng = np.float128(1/np.sqrt(1 - beta**2)*phys.me)
delta = np.float128(1e-3)
T = np.float128(0.000235*1000)
print(series.F1_up_down(beta, delta, T))
print(series.F0_up_down_diff(beta, delta, T))
print(series.F0_up_down_sum(beta, delta, T))
print(series.F0_up_down_diff(beta, delta, T) + series.F0_up_down_sum(beta, delta, T))
print(series.F_inv_up_down(beta, delta, T))
print(series.F_inv2_up_down(beta, delta, T))
print(ics_spec.engloss_spec_diff(eleceng, delta, T))

[[ 5.08973e-11]]
[[-7.63461e-11]]
[[ 1.92147e-11]]
[[-5.71313e-11]]
[[ 7.6346e-11]]
[[-5.08976e-11]]
Computing energy loss spectrum by beta expansion...
(1/5) Computing F1_up - F1_down term...
(2/5) Computing F0_up - F0_down term...
(3/5) Computing F0_up + F0_down term...
(4/5) Computing F_inv_up - F_inv_down term...
(5/5) Computing F_inv2_up - F_inv2_down term...
Computation by expansion in beta complete!
[[ 0.00327028]]


In [31]:
ics_spec.engloss_spec_series(np.array([eleceng], dtype='float128'), np.array([delta], dtype='float128'), 0.235)

Computing energy loss spectrum by analytic series...
Computing upscattering loss spectra...
Computing series 1/7...
Computing series 2/7...
Computing series 3/7...
Computing series 4/7...
Computing series 5/7...
Computing series 6/7...
Computing series 7/7...
Computing downscattering loss spectra...
Computing series 1/7...
Computing series 2/7...
Computing series 3/7...
Computing series 4/7...
Computing series 5/7...
Computing series 6/7...
Computing series 7/7...
***** Diagnostics *****
lowlim_up:  [[ 1.0617]]
lowlim_down:  [[ 1.06596]]
beta:  [ 0.002]
delta/T:  [ 0.00425532]
***** Individual terms *****
term_1_up:  [[ 0.000245099]]
term_0_up:  [[-49.8723]]
term_inv_up:  [[-0.0632631]]
term_log_up:  [[ 49.9354]]
term_1_down:  [[ 0.000244397]]
term_0_down:  [[-49.6088]]
term_inv_down:  [[ 0.0629885]]
term_log_down:  [[ 49.5456]]
***** Upscatter and Downscatter Differences*****
term_1:  [[ 7.02701e-07]]
term_0:  [[-0.263513]]
term_inv:  [[-0.126252]]
term_log:  [[ 0.389764]]
***** Total

array([[ 0.00154503]], dtype=float128)

In [26]:
Emax = np.float128(1e10)
Emin = np.float128(1e-8)
nEe = np.float128(500)
nEp  = np.float128(500)

dlnEp = np.log(Emax/Emin)/nEp
delta = Emin*np.exp((np.arange(nEp)+0.5)*dlnEp)        

dlnEe = np.log(Emax/Emin)/nEe
lowengEe = phys.me + Emin*np.exp((np.arange(nEe)+0.5)*dlnEe)

# lowengEe = np.array([lowengEe[168]],dtype='float128')
# lowengEp = np.array([lowengEp[521]],dtype='float128')
#521
T = np.float128(phys.TCMB(1)*1000)

In [27]:
%%prun
a = ics_spec.engloss_spec(lowengEe, delta, T)


Computing energy loss spectra by analytic series...
Computing upscattering loss spectra...
Computing series 1/7...
Computing series 2/7...
Computing series 3/7...
Computing series 4/7...
Computing series 5/7...
Computing series 6/7...
Computing series 7/7...
Computing downscattering loss spectra...
Computing series 1/7...
Computing series 2/7...
Computing series 3/7...
Computing series 4/7...
Computing series 5/7...
Computing series 6/7...
Computing series 7/7...
 

In [28]:
pickle.dump(a, 
            open("/Users/hongwan/Dropbox (MIT)/Photon Deposition/ICS_englossspec.raw", "wb"))

In [20]:
k = 700
print(np.exp(k)*sp.expn(1,k))
print(1/k-1/k**2+2/k**3)
print(np.exp(k)*sp.expn(2,k))
print(1/k-2/k**2+6/k**3)

0.0014265364183
0.001426536443148688
0.00142450718938
0.0014245072886297377


In [113]:
a = np.array([-1e-8,1e-4, 1])
beta = np.array([1e-8, 1e-3,1.-1e-8])
lowlim1 = np.outer((1-beta)/(2*beta), a)
lowlim2 = np.outer(-(1+beta)/(2*beta), a)
lowlim = np.maximum(lowlim1, lowlim2)
print(lowlim)
print(series.F_log_a(lowlim, a))

[[  5.000000e-01   5.000000e+03   5.000000e+07]
 [  5.005000e-06   4.995000e-02   4.995000e+02]
 [  1.000000e-08   5.000000e-13   5.000000e-09]]
(array([[ 0.0775888,  0.0,  0.0],
       [-73.7552, -3.85918,  7.30347e-217],
       [-170.577, -216.087,  1.11786]], dtype=float128), array([[ 3.84965e-11,  0.0,  0.0],
       [ 5.24232e-12,  6.02323e-11,  0.0],
       [ 2.26671e-12,  9.11894e-11,  1.47179e-11]], dtype=float128))


In [114]:
series.F_x_log(np.array([0.203]), np.array([3.650]))

(array([ 0.0731666], dtype=float128), array([ 1.78408e-11], dtype=float128))

In [116]:
a = np.array([-1e-8,-1e-4,1e-4, 1])
beta = np.array([1e-8, 1e-3,1.-1e-8])
lowlim1 = np.outer((1-beta)/(2*beta), a)
lowlim2 = np.outer(-(1+beta)/(2*beta), a)
lowlim = np.maximum(lowlim1, lowlim2)
print(lowlim)
print(series.F_x_log_a(lowlim, a))

[[  5.000000e-01   5.000000e+03   5.000000e+03   5.000000e+07]
 [  5.005000e-06   5.005000e-02   4.995000e-02   4.995000e+02]
 [  1.000000e-08   1.000000e-04   5.000000e-13   5.000000e-09]]
(array([[ 0.533462,  0.0,  0.0,  0.0],
       [-0.24203, -0.0446386, -0.0443266,  3.65539e-214],
       [-0.242096, -0.241163, -0.241075,  1.27739]], dtype=float128), array([[ 4.71226e-11,  0.0,  0.0,  0.0],
       [ 2.529e-11,  1.06359e-11,  1.07121e-11,  0.0],
       [ 2.52831e-11,  2.53791e-11,  2.53919e-11,  2.87272e-11]], dtype=float128))


In [70]:
np.exp(100)

2.6881171418161356e+43