In [37]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [65]:
%autoreload
import numpy as np
import scipy.special as sp
import darkhistory.electrons.ics.engloss_diff_terms as series
import darkhistory.electrons.ics.bose_einstein_integrals as BE_int
import darkhistory.electrons.ics.ics_engloss_spectrum as ics_spec
import darkhistory.physics as phys
import pickle

np.set_printoptions(precision=15)

In [66]:
beta = np.float128(0.001)
eleceng = np.float128(1/np.sqrt(1 - beta**2)*phys.me)
delta = np.float128(1e-4)
T = np.float128(phys.TCMB(1000))
print(eleceng-phys.me)

print(ics_spec.engloss_spec_diff(eleceng, delta, T))

0.255499664675
Computing energy loss spectrum by beta expansion...
(1/5) Computing F1_up - F1_down term...
(2/5) Computing F0_up - F0_down term...
(3/5) Computing F0_up + F0_down term...
(4/5) Computing F_inv_up - F_inv_down term...
(5/5) Computing F_rem term...
Computation by expansion in beta complete!
[[ 0.00342662293976345]]


In [67]:
ics_spec.engloss_spec(np.array([eleceng], dtype='float128'), 
                             np.array([delta], dtype='float128'), T)

Initializing...
Computing energy loss spectrum by beta expansion...
(1/5) Computing F1_up - F1_down term...
(2/5) Computing F0_up - F0_down term...
(3/5) Computing F0_up + F0_down term...
(4/5) Computing F_inv_up - F_inv_down term...
(5/5) Computing F_rem term...
Computation by expansion in beta complete!
Computing energy loss spectrum by analytic series...
Computing upscattering loss spectra...
Computing series 1/7...
Computing series 2/7...
Computing series 3/7...
Computing series 4/7...
Computing series 5/7...
Computing series 6/7...
Computing series 7/7...
Computing downscattering loss spectra...
Computing series 1/7...
Computing series 2/7...
Computing series 3/7...
Computing series 4/7...
Computing series 5/7...
Computing series 6/7...
Computing series 7/7...
Energy loss spectrum computed!


array([[ 0.003426622939797]], dtype=float128)

In [73]:
Emax = np.float128(1e10)
Emin = np.float128(1e-8)
nEe = np.float128(500)
nEp  = np.float128(500)

dlnEp = np.log(Emax/Emin)/nEp
delta = Emin*np.exp((np.arange(nEp)+0.5)*dlnEp)        

dlnEe = np.log(Emax/Emin)/nEe
lowengEe = phys.me + Emin*np.exp((np.arange(nEe)+0.5)*dlnEe)

# lowengEe = np.array([lowengEe[168]],dtype='float128')
# lowengEp = np.array([lowengEp[521]],dtype='float128')
#521
T = np.float128(phys.TCMB(1)*1000)

In [74]:
%%prun
a = ics_spec.engloss_spec(lowengEe, delta, T)


Initializing...
Computing energy loss spectrum by beta expansion...
(1/5) Computing F1_up - F1_down term...
(2/5) Computing F0_up - F0_down term...
(3/5) Computing F0_up + F0_down term...
(4/5) Computing F_inv_up - F_inv_down term...
(5/5) Computing F_rem term...
Computation by expansion in beta complete!
Computing energy loss spectrum by analytic series...
Computing upscattering loss spectra...
Computing series 1/7...
Computing series 2/7...
Computing series 3/7...
Computing series 4/7...
Computing series 5/7...
Computing series 6/7...
Computing series 7/7...
Computing downscattering loss spectra...
Computing series 1/7...
Computing series 2/7...
Computing series 3/7...
Computing series 4/7...
Computing series 5/7...
Computing series 6/7...
Computing series 7/7...
Energy loss spectrum computed!
 

In [72]:
pickle.dump(a, 
            open("/Users/hongwan/Dropbox (MIT)/Photon Deposition/ICS_englossspec.raw", "wb"))

In [8]:
k = 700
print(np.exp(k)*sp.expn(1,k))
print(1/k-1/k**2+2/k**3)
print(np.exp(k)*sp.expn(2,k))
print(1/k-2/k**2+6/k**3)

0.0014265364183
0.001426536443148688
0.00142450718938
0.0014245072886297377


In [9]:
a = np.array([-1e-8,1e-4, 1])
beta = np.array([1e-8, 1e-3,1.-1e-8])
lowlim1 = np.outer((1-beta)/(2*beta), a)
lowlim2 = np.outer(-(1+beta)/(2*beta), a)
lowlim = np.maximum(lowlim1, lowlim2)
print(lowlim)
print(series.F_log_a(lowlim, a))

[[  5.000000050000000e-01   4.999999950000000e+03   4.999999950000000e+07]
 [  5.005000000000000e-06   4.995000000000000e-02   4.995000000000000e+02]
 [  1.000000005000000e-08   5.000000075123798e-13   5.000000075123797e-09]]


AttributeError: module 'darkhistory.electrons.ics.engloss_diff_terms' has no attribute 'F_log_a'

In [ ]:
series.F_x_log(np.array([0.203]), np.array([3.650]))

In [ ]:
a = np.array([-1e-8,-1e-4,1e-4, 1])
beta = np.array([1e-8, 1e-3,1.-1e-8])
lowlim1 = np.outer((1-beta)/(2*beta), a)
lowlim2 = np.outer(-(1+beta)/(2*beta), a)
lowlim = np.maximum(lowlim1, lowlim2)
print(lowlim)
print(series.F_x_log_a(lowlim, a))

In [ ]:
np.exp(100)