In [21]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [248]:
%autoreload
import numpy as np
from darkhistory.utilities import diff_pow
import darkhistory.electrons.ics.ics_series as ics_series

In [249]:
lowbound = np.array([0.09,1.424e-4, 1.8, 6.5])
uppbound = np.array([0.099, 3.6703, 3.8, 10.3252])
print(ics_series.F1(lowbound, uppbound, epsrel=1e-16))
print(ics_series.F0(lowbound, uppbound, epsrel=1e-16))

[ 0.00858145  1.52446958  0.38943937  0.01091228]
[  9.08810442e-02   8.83114299e+00   1.58056775e-01   1.47177382e-03]


In [51]:
b=6
a=3.4
c = -np.exp(-b) - np.exp(-2*b)/4 - np.exp(-3*b)/9 - np.exp(-4*b)/16
d = -np.exp(-a) - np.exp(-2*a)/4 - np.exp(-3*a)/9 - np.exp(-4*a)/16
test = -np.exp(-b) + np.exp(-a) 
print(c,d)
print(test)

-0.00248028992433 -0.0336559213136
0.0308945177837


In [71]:
n = 1 + np.arange(12)
np.sum((-1)**(n-1)*0.0001**n/n)

9.9995000333308339e-05

In [72]:
np.log(1+0.0001)

9.9995000333297321e-05

In [189]:
a = np.array([2,4,5,6,10])
b = np.array([3,7,9,20,25])
integral = np.arange(5)
print(integral[~((a < 5) | (b > 10))])

[2]


In [190]:
print(a < 5)

[ True  True False False False]


In [191]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [208]:
a = np.array([True, False, False])
print(np.all(a) == False)

True
