In [1]:
%load_ext autoreload

In [195]:
%autoreload
import numpy as np
from darkhistory.utilities import diff_pow
from darkhistory.utilities import compare_arr
import darkhistory.electrons.ics.ics_nonrel_series as series
import darkhistory.electrons.ics.ics_nonrel as nonrel
import darkhistory.physics as phys

np.set_printoptions(precision=20)

In [196]:
#510998.94610007945
eleceng = np.array([510999],dtype=np.float128)
photeng = np.array([7.94328e-7],dtype=np.float128)
T = np.float128(phys.TCMB(1)*1000)
print(nonrel.spec_series(eleceng, photeng, T))
print(nonrel.spec_quad(eleceng, photeng, T))
print(nonrel.spec_diff(eleceng, photeng, T))

[[ 4.9091665540351580864e-08]]


A Jupyter Widget

[[  4.90920065908781955664e-08]]
beta:  [ 0.00045930306535217845445]
(array([[ 4.9091997673769247989e-08]], dtype=float128), array([[-8.8975472180044040337e-22]], dtype=float128))


In [197]:
Emax = 1e10
Emin = 1e-8
nEe = 5
nEp  = 5

dlnEp = np.log(Emax/Emin)/nEp
lowengEp = Emin*np.exp((np.arange(nEp)+0.5)*dlnEp)        

dlnEe = np.log(Emax/Emin)/nEe
lowengEe = phys.me + Emin*np.exp((np.arange(nEe)+0.5)*dlnEe)

T = np.float128(phys.TCMB(1)*1000)

In [198]:
# %%prun
nonrel.spec_series(lowengEe, lowengEp, T)

/Users/hongwan/GitHub/DarkHistory/darkhistory/electrons/ics/ics_nonrel_series.py:341: RuntimeWarning: invalid value encountered in true_divide
  err = np.max(np.abs(next_term/integral[both_high]))
/Users/hongwan/GitHub/DarkHistory/darkhistory/electrons/ics/ics_nonrel_series.py:468: RuntimeWarning: invalid value encountered in true_divide
  err = np.max(np.abs(next_term/integral[both_high]))


array([[  2.93301362340954732133e+01,  -6.32184002672751303180e+04,
         -2.20694936287270831551e-12,   0.00000000000000000000e+00,
          0.00000000000000000000e+00],
       [  2.73460915287730314677e-06,   1.56701470948844546159e-03,
          9.00445228830939275553e-18,   0.00000000000000000000e+00,
          0.00000000000000000000e+00],
       [  3.89947997909399421857e-08,   1.54411631724869541273e-04,
          8.90076949445308440013e-18,   0.00000000000000000000e+00,
          0.00000000000000000000e+00],
       [  3.63119644857066943296e-08,   1.43685819343061717702e-04,
          1.45350673861913760055e-10,   0.00000000000000000000e+00,
          0.00000000000000000000e+00],
       [  3.81257050467476283098e-12,   6.66264718398543993703e-09,
          1.84101440614425308666e-07,   5.58829529190188986833e-08,
          0.00000000000000000000e+00]])

In [203]:
# %%prun
lowengEe = np.array([510998.947, 510998.99, 510999])
lowengEp = np.array([3e-7])
test_spec_diff = nonrel.spec_diff(lowengEe, lowengEp, T)
print(test_spec_diff)
compare_arr([test_spec_diff[0],test_spec_diff[1]])

beta:  [  5.93507543962915965212e-05   4.14512114556605647947e-04
   4.59303065447072013903e-04]
(array([[  1.85409757905380787898e-08],
       [  1.85409743343469449440e-08],
       [  1.85409739956977992665e-08]]), array([[ -9.36919121408143964411e-26],
       [ -2.22918377468817023495e-22],
       [ -3.36042571521665035456e-22]]))
[[[  1.85409757905380787898e-08  -9.36919121408143964411e-26]]

 [[  1.85409743343469449440e-08  -2.22918377468817023495e-22]]

 [[  1.85409739956977992665e-08  -3.36042571521665035456e-22]]]


0

In [182]:
print(nonrel.spec_quad(lowengEe, lowengEp, T))

A Jupyter Widget

/Users/hongwan/anaconda/envs/python3/lib/python3.6/site-packages/scipy/integrate/quadpack.py:364: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  warnings.warn(msg, IntegrationWarning)
/Users/hongwan/anaconda/envs/python3/lib/python3.6/site-packages/scipy/integrate/quadpack.py:364: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  warnings.warn(msg, IntegrationWarning)


KeyboardInterrupt: 

In [122]:
a = np.array([[1,0,2],[0,1,3]])
print(a.ndim)
print(a.shape)
b = np.zeros(a.shape)
print(b)

2
(2, 3)
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [184]:
lowbound = np.array([2.3e-8, 0.09,1.424e-4, 1.8, 6.5, 1.32930])
uppbound = np.array([3.394e-4, 0.099, 3.6703, 3.8, 10.3252, 3.492e8])
print(series.F1(lowbound, uppbound, epsrel=1e-16))
print(series.F0(lowbound, uppbound, epsrel=1e-16))
print(series.F_inv(lowbound, uppbound))
print(series.F_log(lowbound, uppbound))

lowbound = np.array([[2.3e-8, 0.09],[1.424e-4, 1.8], [6.5, 1.32930]])
uppbound = np.array([[3.394e-4, 0.099],[3.6703, 3.8], [10.3252, 3.492e8]])
print(series.F1(lowbound, uppbound, epsrel=1e-16))


lowbound = np.array([[2.3e-8, 0.09],[1.424e-4, 1.8], [6.5, 1.32930]])
uppbound = np.array([3.394e-4, 0.099])
print(series.F1(lowbound, uppbound, epsrel=1e-16))

[  3.39348202996140246510e-04   8.58145174882529726545e-03
   1.52446957950191541720e+00   3.89439368845468814051e-01
   1.09122842821987361267e-02   6.93265248905243103295e-01]
[  9.59927073215279591523e+00   9.08810442338062046685e-02
   8.83114298512566620047e+00   1.58056775020700729373e-01
   1.47177382268633008891e-03   3.07425647356494746720e-01]
[  4.34753096939157173038e+07   9.63195808510190154550e-01
   7.01740740206419832248e+03   6.68199856379011331020e-02
   2.00676595044219167321e-04   1.54557027804291646778e-01]
[ -1.22756612509525538712e+02  -2.14508965826628095197e-01
  -3.85333212922386607602e+01   1.39207249164719076839e-01
   2.94028704356445388934e-03   2.28614115581175780800e-01]
