In [3]:
%load_ext autoreload

In [9]:
%autoreload
import numpy as np
from darkhistory.utilities import diff_pow
from darkhistory.utilities import compare_arr
import darkhistory.electrons.ics.ics_nonrel_series as series
import darkhistory.electrons.ics.ics_nonrel as nonrel
import darkhistory.physics as phys

np.set_printoptions(precision=10)

In [10]:
#510998.94610007945
eleceng = np.array([510998.947, 511002, 512000],dtype=np.float128)
photeng = np.array([7.94328e-7, 7.93248e-5, 7.94328e-2],dtype=np.float128)
T = np.float128(phys.TCMB(1)*1000)
print(nonrel.spec_series(eleceng, photeng, T))
print(nonrel.spec_quad(eleceng, photeng, T))
print(nonrel.spec_diff(eleceng, photeng, T)[0])
print('**********Full Method:************')
# print(nonrel.nonrel_spec(eleceng, photeng, T))

[[ 5.36209978e-08  5.354717063e-06 -0.04070988522]
 [ 4.909172954e-08  4.901679164e-06  0.00412613796]
 [ 4.900236902e-08  4.892753965e-06  0.004116278381]]


A Jupyter Widget


[[  4.9081587402e-08   4.9006667782e-06   4.1253009422e-03]
 [  4.9091501571e-08   4.9016563820e-06   4.1261453400e-03]
 [  4.9008335033e-08   4.8925924319e-06   4.1162783812e-03]]
[[ 4.909200243e-08  4.901706469e-06  0.004126190111]
 [ 4.909172867e-08  4.901679127e-06  0.004177815712]
 [ 4.900200495e-08  4.892717715e-06  0.0209057463]]
**********Full Method:************


In [14]:
Emax = 1e10
Emin = 1e-8
nEe = 1
nEp  = 1

dlnEp = np.log(Emax/Emin)/nEp
lowengEp = Emin*np.exp((np.arange(nEp)+0.5)*dlnEp)        

dlnEe = np.log(Emax/Emin)/nEe
lowengEe = phys.me + Emin*np.exp((np.arange(nEe)+0.5)*dlnEe)

T = np.float128(phys.TCMB(1)*1000)
print(lowengEe)
print(lowengEp)
print(T)

[ 511008.9461]
[10.]
0.235


In [15]:
%%prun
nonrel.nonrel_spec(lowengEe, lowengEp, T)

beta < 0.01:  [ True]
eta < 1:  [False]
where_diff on (eleceng, photeng) grid: 
[[False]]
Computed spectrum from spec_diff: 
[]
Computed relative error from spec_diff: 
[]
spec: 
[[ 0.]]
epsrel: 
[[ 0.]]
where_series on (eleceng, photeng) grid: 
[[ True]]
Computed spectrum from spec_series: 
[  8.9007694945e-18]
*********************
Final Result: 
[[  8.9007694945e-18]]
 

In [16]:
%%prun
print(nonrel.spec_quad(lowengEe, lowengEp, T))

A Jupyter Widget


[[  8.9006571670e-18]]
 

In [ ]:
# %%prun
nonrel.spec_series(lowengEe, lowengEp, T)

In [ ]:
# %%prun
lowengEe = np.array([510998.947, 510998.99, 510999])
lowengEp = np.array([3e-7])
test_spec_diff = nonrel.spec_diff(lowengEe, lowengEp, T)
print(test_spec_diff)
compare_arr([test_spec_diff[0],test_spec_diff[1]])

In [ ]:
a = np.array([[1,0,2],[0,1,3]])
a[a >= 1] = a[a >= 1]*2
print(a)

In [ ]:
lowbound = np.array([2.3e-8, 0.09,1.424e-4, 1.8, 6.5, 1.32930])
uppbound = np.array([3.394e-4, 0.099, 3.6703, 3.8, 10.3252, 3.492e8])
print(series.F1(lowbound, uppbound, epsrel=1e-16))
print(series.F0(lowbound, uppbound, epsrel=1e-16))
print(series.F_inv(lowbound, uppbound))
print(series.F_log(lowbound, uppbound))

lowbound = np.array([[2.3e-8, 0.09],[1.424e-4, 1.8], [6.5, 1.32930]])
uppbound = np.array([[3.394e-4, 0.099],[3.6703, 3.8], [10.3252, 3.492e8]])
print(series.F1(lowbound, uppbound, epsrel=1e-16))


lowbound = np.array([[2.3e-8, 0.09],[1.424e-4, 1.8], [6.5, 1.32930]])
uppbound = np.array([3.394e-4, 0.099])
print(series.F1(lowbound, uppbound, epsrel=1e-16))