In [1]:
%load_ext autoreload
import sys
sys.path.append("..")

In [31]:
%autoreload

import matplotlib
matplotlib.rc_file('matplotlibrc')
import matplotlib.pyplot as plt

%matplotlib inline

matplotlib.rcParams['figure.figsize'] = [10,10]


from astropy.io import fits

import numpy as np
import pickle
import darkhistory.physics as phys
import darkhistory.utilities as utils
import darkhistory.spec.spectools as spectools
import darkhistory.spec.transferfunction as tf
from darkhistory.spec.spectrum import Spectrum
from darkhistory.spec.spectra import Spectra
import darkhistory.history.tla as tla

from darkhistory.electrons.ics.ics_spectrum import ics_spec
from darkhistory.electrons.ics.ics_engloss_spectrum import engloss_spec
from darkhistory.electrons.ics.ics_cooling import get_ics_cooling_tf

np.set_printoptions(threshold=np.nan)

In [32]:
eng = np.array([1, 2, 3, 4, 5])
a = Spectrum(eng, np.array([2, 4, 6, 8, 10]))
b = Spectrum(eng, np.array([1, 2, 3, 4, 5]))

In [33]:
print(a.totN())
a.switch_spec_type()
print(a.totN())
a.switch_spec_type()
print(a.totN())

31.349455686798166
31.349455686798166
31.349455686798166


In [34]:
c = Spectra([a, b])
print(c.totN())

[31.34945569 15.67472784]


In [35]:
print('before switch')
print(c._grid_vals)
print(c.spec_type)
print(c[0].N)
print(c[1].N)
c.switch_spec_type()
print('after switch')
print(c.spec_type)
print(c._grid_vals)
print(c[0].N)
print(c[1].N)

print('******')

print(c.totN())
c.switch_spec_type()
print(c.totN())

before switch
[[ 2.  4.  6.  8. 10.]
 [ 1.  2.  3.  4.  5.]]
dNdE
[ 1.38629436  4.39444915  6.23832463  8.17320998 11.15717757]
[0.69314718 2.19722458 3.11916231 4.08660499 5.57858878]
after switch
N
[[ 1.38629436  4.39444915  6.23832463  8.17320998 11.15717757]
 [ 0.69314718  2.19722458  3.11916231  4.08660499  5.57858878]]
[ 1.38629436  4.39444915  6.23832463  8.17320998 11.15717757]
[0.69314718 2.19722458 3.11916231 4.08660499 5.57858878]
******
[31.34945569 15.67472784]
[31.34945569 15.67472784]
